### ISSUE TITLE
ToUTMPolyline method is quite slow

### ISSUE THREAD

**Issue by rwemay** [BHoM/OpenStreetMap_Toolkit#30]
#### Description:

Had a quick look at the code but couldn't immediately see why - seems odd?!

**Comment by rolyhudson** [comment]
Agreed it is slow sometimes frustrating. Currently using [this](https://github.com/Tronald/CoordinateSharp) lib to handle the conversions. Converting lat, lon to utm is a bit of a lengthy process. [This snippet](https://stackoverflow.com/a/16660841/3561565) and the discussion and links within gives a sense of what is involved. 

Would be good to get some GIS expertise (Anthony T, who else?) On how we could improve - maybe add options for faster more approximate methods projecting to a simple sphere not complex ellipsoids.

**Comment by rwemay** [comment]
Just a thought on this - have you already parallelised it if it can be? I've been using .AsParallel() on Linq methods to great effect for parallel heavy methods.

**Comment by rolyhudson** [comment]
Nice idea. Going to have a look at this do some performance tests see if we can speed it up a bit.

**Comment by rolyhudson** [comment]
It is an improvement of 2.5 times speed:
![2020-06-12_09-54-33](https://user-images.githubusercontent.com/6618854/84484625-ebd48e80-ac92-11ea-9bf7-5fb8990fdeac.jpg)
