### ISSUE TITLE
Remove use of CustomData in the code

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/OpenStreetMap_Toolkit#50]
The files listed below have been detected as having code using `CustomData`. This detection has been automatic, and may have picked up on code comments or documentation. Please review each file carefully and remove all instances of `CustomData`.

This should be completed by the 30th October 2020.

<details>
<summary>Full list</summary>
<p>

 - [ ] OpenStreetMap_Toolkit\OpenStreetMap_Engine\Convert\ToElementContainer.cs

</p>
</details>

**Comment by rolyhudson** [comment]
Noting here that the removal of `CustomaData` in OpenStreetMap_Toolkit is dependent on the same issue in the Serialiser_Engine https://github.com/BHoM/BHoM_Engine/issues/2077 and HTTP_Toolkit https://github.com/BHoM/HTTP_Toolkit/issues/57.

OpenStreetMap_Toolkit methods with `CustomData`  in the code are converts handling `CustomObject`s that include `CustomData` returned by `Serialiser.Convert.FromJson` and results of a Pull request with the HTTP_Adapter.

**Comment by rolyhudson** [comment]
Further note following discussion 22/10/2020. 
Detected use of `CustomData` in this toolkit is in a method that parses incoming `CustomObject`s.  There is no assignment to `CustomData`. 

Each parsed  `CustomObject` contains data returned by the OpenStreetMap server and converted to `CustomObject` by the HTTP_Toolkit calling `FromJson`.

I believe usage here should be considered inevitable. Does that sound reasonable @FraserGreenroyd ?

**Comment by FraserGreenroyd** [comment]
It does, in that case you'll want to rename `CustomData` to whatever @adecler renames it to when he closes out the BHoM issue, and align with him rather than change in advance :smile:

**Comment by FraserGreenroyd** [comment]
Since determined not to rename custom data is usage in this toolkit is valid.
